#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 29 20:45:48 2021

@author: Park
"""

from random import randint
import random
import numpy as np
# Finding the highest value among the lowest values in each row
n, m = map(int,input().split()) # n by m matrix 


matrix = [[randint(1,50) for ___ in range(n)] for ___ in range(m)] # Generating n by m random matrix

matrix = np.array(matrix)

lowest = [] #List which will save the lowest values in each raw


for i in range(n):
    lowest.append(min(matrix[i,:]))
    
print(max(lowest)) # Printing Highest value among the lowest values 